// <auto-generated />
namespace SimpleTodo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddedMattEntity : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207312042445_AddedMattEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so9fFYlXmb6pZNZbGH6XHZZERIq/z8vw9sdp5CKw+sv1Rj6eEWXv95nqVc6+fffS8uvhyyV357ajl75VfBx/QRy/rapXX7fWr/FzfPpt9lN4N37vbfdG+5r0DBOi3Zfvp/kfpi3VZZpOSPjjPyib/KF19+uh1W9X55/kyr7M2n73M2javl3g35wEoIR6tPr0dLR7e3dkDLe5my2XVZi1Ncw/xDppfNXmN3wyyr9uauOaj9FnxLp89z5cX7dwi/EX2znyyv7NDzPPVsiAuo7faep1HRri569NFVpTfbL/y9+ZuX2ZNc1XVdnpu2fPuhw/4Vb7IF5O8/sJS+0lVlXm2fG9IJ3UOhjFgntIfbwpM4nvC+Wo1+xpwHt918rVR6iDgZ20eyOaPZO4j0pQtdfaeDPgNsP5rwm/d/PD7/X8zu2IysoK4wZ+cd22HZaXt67z11CYR0gEWyzX27Ex3LF0Qz4umjUCwMhMdg8XWWde7Yl6NGb47YIcff5GtVjTfnl3WT9LXYpRPtl+/v+VdCIy70yZigC22tieSvewi73wLos/yZ0XdtDSl2STDDJ7MFpFmG+fG9OJPUVfROHqb1vhdxaPrlfjT2QHkyPeMRrQgcebB6dAImWGfQ19/Pc3KrI5osJOqXC+WQ1pw09vOmPsw3Ke3h6S22QejH90ehjO0Phj36e0h+YbTh+V/fntoVhv5oOyHt4djtVFAbPNhH87jux2O6fKmp6e0Zcf+dTn9VnLAeubDxCBuxxnQTUIw/OrPjghY2xpMrvnw9nCMqfTBmM9uD+X/l6zWs0XdJrZ3a5M6tuex2oHAQPHYu4FizzBIk49SItBlMYNReH3dEH+N0WD8+heVr/OaIuGTfLyP8NY0+yJbFud5076p3ubk7PF3XzfitB5f08wC1f7/rrBzUlwU4Pkb/d33dcI6EePyMqun86yOOI3vCTkICG8F9jbOZzfeiwLe/Rro9sO5SdG+N5SObwyRRlblveF0fONbwvn/QCj3s8XHnSjsG+O3MMj6xsD+v5lP+jFU150PUbLGpa8mN4dUov0J60lFAxBs3fc909zryAVXvW7cV7FOzLedLt4jLOubvMd3/Qzq46d5U1w4EMinLvMp8gkOqGlztjyvzLzS6HyMTJPOtH+RtxnNdXZct8V5Nm3p62neNJwA+MmsXOdQv5N8drb8ct2u1u1x05ByK6/98T6+u7l/jj1DnB9/ucJfno3/+kMgNAuw65fLJ+uinFm8n0XYdQAEGFNVCGFFCRACd3FtIb2olrcEpOR7mq/yJRTQm5x8ZgLWfLl8nV3mw7jdTMOQYo+fFtlFnS18CsonisnrDN6664I68N9w/dGfxK6Uvj/6fwIAAP//0uTgpzMYAAA="; }
        }
    }
}
