// <auto-generated />
namespace SimpleTodo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class RemoveIsChecked : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207310229086_RemoveIsChecked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so9fFYlXmb6pZNZbGH6XHZZERIq/z8vw9sdp5CKw+sv1Rj6eEWXv95nqVc6+fffS8uvhyyV357ajl75VfBx/QRy/rapXX7fWr/FzfPpt9lN4N37vbfdG+5r0DBOi3ZXtv76P0xboss0lJH5xnZZN/lK4+ffS6rer883yZ11mbz15mbZvXS7yb8wCUEI9Wn96OFg/v7uyBFnez5bJqs5amuYd4B82vmrzGbwbZ121NXPNR+qx4l8+e58uLdm4R/iJ7Zz7Z39kh5vlqWRCX0Vttvc4jI9zc9ekiK8pvtl/5e3O3L7OmuapqOz237Hn3wwf8Kl/ki0lef2Gp/aSqyjxbvjekp8QuJ3UOpjGg8NGbAhO5Edbju042NkoMhPOszQO5+pG8fERarqXO3pN5vgG2fU34rZsffr8/W6wGQmYFzaRP2Hdth92k7eu89dQVEcEBFosx9vR7dzxdEGDs50XTRqBYno+Ow2LsLNtdMW3GBN4dsIGPv8hWK5ovzybqJ+lrMYgn26/f3+otBMbdaRMxfhZb2xPJTnaRd74F4Wf5s6JuWprWbJJhFk9mi0izjfNjevGnqasoHL1Na/yu7N31CPwp7QBy5HtGI1qQOPLgdGiEzLC919dfT7MyqyMa6KQq14vlkBbb9LYzpD4M9+ntIald9MHoR7eH4YycD8Z9entIvtHyYfmf3x5aoE18cMEXfXiP73ZmvMtbnq7Rlh370+XUW/Gx1RUfxspxW8qAbmLk4Vd/dtjY2jcfhP3w9nCMufLBmM9uD+X/lezSswfdJrZ3axc6+v+x6uLASDANuoFSTzlLk49SItRlMYNifn3dEH+M0WD8+heVr/OaIsGTfLyP8M40+yJbFud5076p3ubkMPF3Xzfisl5T08wC9fr/rrCrAMPe6DC+p+PdDZeWl1k9nWd1xOt6T8hBNHQrsLfx3rrBThTw7tdAtx/LTIr2vaFEnMsZ/YG0wgc5l/+viGN+VhiwE398Y4wShhffGNifrQnuRw9dJzZEy6rzvmLaHEyIviWsJxUNQLB13/eMWTTakJCi1437KtaJ+bbTxXsEI30j8/iun7N7/DRvigsHAhm8ZT5FFOyAmjZny/PKzC2NzsfINOlM/Rd5m9FcZ8d1W5xn05a+nuZNw2HrT2blOofOm+Szs+WX63a1bo+bhjRKee2P9/Hdzf1zxBXi/PjLFf7yrOrXHwKhWYBdv1w+WRflzOL9LMKuAyDAmCr+hBWF7QTu4tpCelEtbwlIyfc0X+VLKI83OXmZBKz5cvk6u8yHcbuZhiHFHj8tsos6W/gUlE+Mqsjg37ouqAP/Ddcf/UnsSgnjo/8nAAD//3pLrO+lFgAA"; }
        }
    }
}
