// <auto-generated />
namespace SimpleTodo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddTestBool : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208011723096_AddTestBool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so9fFYlXmb6pZNZbGH6XHZZERIq/z8vw9sdp5CKw+sv1Rj6eEWXv95nqVc6+fffS8uvhyyV357ajl75VfBx/QRy/rapXX7fWr/FzfPpt9lN4N37vbfdG+5r0DBOi3Zfvp/kfpi3VZZpOSPjjPyib/KF19+uh1W9X55/kyr7M2n73M2javl3g35wEoIR6tPr0dLR7e3dkDLe5my2XVZi1Ncw/xDppfNXmN3wyyr9uauOaj9FnxLp89z5cX7dwi/EX2znyyv7NDzPPVsiAuo7faep1HRri569NFVpTfbL/y9+ZuX2ZNc1XVdnpu2fPuhw/4Vb7IF5O8/sJS+0lVlXm2fG9Ib/KmxbsfCuekzsF4BsxT+uNNAWZ4TzhfrWZfA87ju05ON0ovFMVZmwcy/iPZ/Yg0bkudvScjfwMi9JrwWzc//H7/38yumIysIG7wJ+dd22FZafs6bz31S4R0gMUCjj171R1LF8TzomkjEKzMRMdgsXVW+q6YaWPO7w7Y88dfZKsVzbdn3/WT9LUY95Pt1+9vwRcC4+60iRhyi63tiWQvu8g734Los/xZUTctTWk2yTCDJ7NFpNnGuTG9+FPUVTSO3qY1flfx6Ho3/nR2ADnyPaMRLUiceXA6NEJm2HfR119PszKrIxrspCrXi+WQFtz0tnMKfBju09tDUhvvg9GPbg/DGWwfjPv09pB8A+zD8j+/PTRnhH1Y7tPbQ7J6zQdkP7w9HKvXgmkzH/bhPL7b4b0ul3saT1t2LGlXZm4lUayxPkyg4h4BA7pJnIZf/dkRJmulg8k1H94ejjG6Phjz2e2h/P+S1XpWrdvE9m6tW8eKPVaLEpg6Hns3dO2ZGGnyUUoEuixmMC+vrxvirzEajF//ovJ1XlNsfpKP9xFwm2ZfZMvinHTFm+ptTm4jf/d1Y2DrOzbNLDAS/+8KhCfFRQGev9Fzfl93rhPDLi+zejrP6oj7+Z6QgxD1VmBv48Z2I9Ao4N2vgW4/wJwU7XtD6QaXXwdGx1OHWkCu6L3hdDz1W8L5/0Bg+bMlC52Y8Bvj2TDk+8bA/r+ZT/oRXTe4CFGyBqqvajcHeGJBCOtJRQMQbN33PfPe68iFer1u3FexTsy3nS7eI0jsm83Hd/288OOneVNcOBDIEi/zKbIbDqhpc7Y8r8y80uh8jEyTzrR/kbcZzXV2XLfFeTZt6etp3jScjvjJrFznUOGTfHa2/HLdrtbtcdOQgiyv/fE+vru5f46EQ5wff7nCX56f8PWHQGgWYNcvl0/WRTmzeD+LsGsEhGFMVSGEFaVjCNzFtYX0olreEpCS72m+ypdQQG9y8rsJWPPl8nV2mQ/jdjMNQ4o9flpkF3W28Ckonxh1k8Hjd11QB/4brj/6k9iVFiWO/p8AAAD//xyVO4EJGQAA"; }
        }
    }
}
